### ISSUE TITLE
Serve content only for given (sub)domain

### ISSUE THREAD

**Issue by dst78** [grisu48/orion#8]
I guess this is related to https://github.com/grisu48/orion/issues/4 but not the same.

I have orion configured to only one subdomain:

```
Hostname = laniakea.rodoste.de
Bind = :1965
``` 

[edit to clarify]
But both the subdomain and `gemini://rodoste.de` will point to orion. The problem is that my certificate is only for laniakea. 

It'd be nice if orion wouldn't serve the configured subdomains content if the request was for another one but instead would throw gemini response code 53 as per spec.

Maybe there already is a way to configure orion in this way?

**Comment by grisu48** [comment]
Hi @dst78, thanks for reporting this issue.

Currently this is not yet possible, but this is basically the same as I want to do in https://github.com/grisu48/orion/issues/4. Currently there is no time plan for this feature, but since I know that there are more people interested in it, this might happen one fine day :slightly_smiling_face:

**Comment by grisu48** [comment]
This issue is now being handled in https://codeberg.org/grisu48/orion/issues/3
